// SQL strings for pg-plan-diagram demo
// Edit this file to add ENTER and indentation manually.
// Use backtick (template literal) formatting.
export const sqlData = [
  `EXPLAIN (ANALYZE, COSTS, BUFFERS) SELECT metric_name, date_trunc('day', recorded_at), AVG(value), MAX(value), MIN(value), COUNT(*) FROM metrics GROUP BY metric_name, date_trunc('day', recorded_at);`,
  `EXPLAIN (ANALYZE, COSTS, BUFFERS, FORMAT JSON) SELECT metric_name, date_trunc('day', recorded_at), AVG(value), MAX(value), MIN(value), COUNT(*) FROM metrics GROUP BY metric_name, date_trunc('day', recorded_at);`,
  `SELECT metric_name, avg(value), max(value), min(value), count(*) FROM metrics GROUP BY metric_name;`,
  `SELECT event_type, count(*), count(DISTINCT user_id) FROM events GROUP BY event_type ORDER BY count(*) DESC;`,
  `SELECT session_id, count(*) AS error_count FROM logs WHERE message ILIKE '%error%' OR message ILIKE '%fail%' OR message ILIKE '%timeout%' GROUP BY session_id ORDER BY error_count DESC;`,
  `SELECT u.id, u.name, (SELECT count(*) FROM posts WHERE fk_user_id = u.id) AS post_count, (SELECT count(*) FROM comments WHERE fk_user_id = u.id) AS comment_count, (SELECT count(*) FROM friends WHERE user_id = u.id OR friend_id = u.id) AS friend_count FROM users_profile u ORDER BY u.id;`,
  `SELECT u.name, p.content AS post_content, p.created_at AS post_date, c.content AS comment_content, c.created_at AS comment_date, cu.name AS commenter_name FROM users_profile u JOIN posts p ON p.fk_user_id = u.id JOIN comments c ON c.fk_post_id = p.id JOIN users_profile cu ON cu.id = c.fk_user_id ORDER BY u.id, p.created_at;`,
  `SELECT u.id AS user_id, u.name AS user_name, f2.friend_id AS friend_of_friend_id, uf.name AS friend_of_friend_name FROM users_profile u JOIN friends f1 ON f1.user_id = u.id JOIN friends f2 ON f2.user_id = f1.friend_id JOIN users_profile uf ON uf.id = f2.friend_id WHERE u.id <> f2.friend_id ORDER BY u.id;`,
  `SELECT a.metric_name, a.recorded_at AS current_ts, a.value AS current_value, b.recorded_at AS previous_ts, b.value AS previous_value, (a.value - b.value) / NULLIF(b.value, 0) * 100 AS pct_change FROM metrics a JOIN metrics b ON b.metric_name = a.metric_name AND b.recorded_at = (SELECT max(recorded_at) FROM metrics WHERE metric_name = a.metric_name AND recorded_at < a.recorded_at) ORDER BY a.metric_name, a.recorded_at;`,
  `SELECT u.name, p.content, p.created_at FROM users_profile u JOIN posts p ON p.fk_user_id = u.id;`,
  `SELECT u.name, p.id AS post_id, p.content FROM users_profile u LEFT JOIN posts p ON p.fk_user_id = u.id ORDER BY u.name;`,
  `SELECT p.id AS post_id, u.name AS commenter, c.content FROM comments c RIGHT JOIN posts p ON p.id = c.fk_post_id LEFT JOIN users_profile u ON u.id = c.fk_user_id;`,
  `SELECT COALESCE(f1.user_id, f2.friend_id) AS user_id, COALESCE(f1.friend_id, f2.user_id) AS friend_id FROM friends f1 FULL OUTER JOIN friends f2 ON f2.user_id = f1.friend_id AND f2.friend_id = f1.user_id WHERE f1.user_id IS NULL OR f2.user_id IS NULL;`,
  `SELECT f1.user_id AS user_a, f2.friend_id AS suggested_friend, count(*) AS mutual_count FROM friends f1 JOIN friends f2 ON f2.user_id = f1.friend_id WHERE f2.friend_id <> f1.user_id AND (f1.user_id, f2.friend_id) NOT IN (SELECT user_id, friend_id FROM friends) GROUP BY f1.user_id, f2.friend_id ORDER BY mutual_count DESC;`,
  `SELECT u.id AS user_id, e_types.event_type, count(e.id) AS event_count FROM users_profile u CROSS JOIN (SELECT DISTINCT event_type FROM events) e_types LEFT JOIN events e ON e.user_id = u.id AND e.event_type = e_types.event_type GROUP BY u.id, e_types.event_type ORDER BY u.id, e_types.event_type;`,
  `SELECT u.id, u.name, u.email FROM users_profile u WHERE EXISTS (SELECT 1 FROM comments c WHERE c.fk_user_id = u.id);`,
  `SELECT u.id, u.name, u.email FROM users_profile u WHERE NOT EXISTS (SELECT 1 FROM posts p WHERE p.fk_user_id = u.id);`,
  `SELECT p.id AS post_id, c.id AS comment_id, c.content AS comment_text, u.name AS commenter FROM posts p CROSS JOIN LATERAL (SELECT id, content, fk_user_id FROM comments WHERE fk_post_id = p.id ORDER BY created_at DESC LIMIT 3) c JOIN users_profile u ON u.id = c.fk_user_id ORDER BY p.id, c.id;`,
  `SELECT u.id, u.name, count(DISTINCT p.id) AS total_posts, count(DISTINCT c.id) AS total_comments_received, count(DISTINCT fr.user_id) AS friend_count FROM users_profile u LEFT JOIN posts p ON p.fk_user_id = u.id LEFT JOIN comments c ON c.fk_post_id = p.id LEFT JOIN friends fr ON fr.friend_id = u.id GROUP BY u.id, u.name ORDER BY total_posts DESC;`,
  `INSERT INTO users_profile (email, name) VALUES ('alice@example.com', 'Alice');`,
  `INSERT INTO logs (session_id, message, timestamp) SELECT session_id, message, timestamp FROM events WHERE event_type = 'page_view';`,
  `INSERT INTO users_profile (id, email, name) VALUES (42, 'bob@example.com', 'Bob') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name;`,
  `INSERT INTO metrics_summary (metric_name, avg_val, max_val, min_val, cnt) SELECT metric_name, avg(value), max(value), min(value), count(*) FROM metrics GROUP BY metric_name;`,
  `UPDATE users_profile SET name = upper(name) WHERE email LIKE '%@example.com';`,
  `UPDATE users_profile SET email = 'new@example.com' WHERE id = 1001;`,
  `UPDATE posts SET content = content || '

[archived]' FROM users_profile WHERE posts.fk_user_id = users_profile.id AND users_profile.email IS NULL;`,
  `UPDATE friends SET created_at = now() WHERE user_id = 42 RETURNING user_id, friend_id, created_at;`,
  `DELETE FROM logs WHERE message LIKE '%timeout%';`,
  `DELETE FROM events WHERE id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';`,
  `DELETE FROM comments WHERE fk_post_id IN (SELECT id FROM posts WHERE created_at < '2023-01-01');`,
  `DELETE FROM friends USING users_profile WHERE friends.friend_id = users_profile.id AND users_profile.email IS NULL;`,
  `SELECT * FROM generate_series(1, 1000);`,
  `SELECT * FROM (VALUES (1, 'Alice'), (2, 'Bob'), (3, 'Carol')) AS t(id, name);`,
  `SELECT metric_name, recorded_at FROM metrics WHERE metric_name = 'cpu';`,
  `SELECT * FROM logs WHERE created_at >= '2024-01-01' AND created_at < '2024-02-01';`,
  `WITH user_counts AS (SELECT user_id, count(*) AS cnt FROM events GROUP BY user_id) SELECT avg(cnt) FROM user_counts;`,
  `SELECT * FROM (SELECT id, name FROM users_profile WHERE email IS NOT NULL) AS active_users;`,
  `SELECT * FROM metrics WHERE ctid = '(100,10)';`,
  `SELECT * FROM logs TABLESAMPLE SYSTEM (1);`,
  `SELECT * FROM metrics_2024_q1 UNION ALL SELECT * FROM metrics_2024_q2;`,
  `SELECT * FROM metrics_2024_q1 UNION ALL SELECT * FROM metrics_2024_q2 ORDER BY recorded_at;`,
  `SELECT DISTINCT metric_name FROM metrics;`,
  `SELECT id, event_type FROM events EXCEPT SELECT id, event_type FROM events_archive;`,
  `SELECT metric_name, recorded_at, value, avg(value) OVER (PARTITION BY metric_name ORDER BY recorded_at ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg FROM metrics WHERE metric_name = 'cpu';`,
  `SELECT u.id, g.value FROM users_profile u, generate_series(1, 10) g(value);`,
  `SELECT u.name, (SELECT count(*) FROM events e WHERE e.user_id = u.id) AS event_count FROM users_profile u WHERE u.email IS NOT NULL;`,
  `SELECT recorded_at, metric_name, avg(value) FROM metrics WHERE recorded_at >= '2024-01-01' GROUP BY recorded_at, metric_name ORDER BY recorded_at, metric_name;`,
  `SELECT * FROM metrics ORDER BY recorded_at DESC LIMIT 10;`,
  `SELECT * FROM foreign_data.users WHERE active = true;`,
  `SELECT metric_name, avg(value) FROM metrics WHERE recorded_at >= '2024-01-01' GROUP BY metric_name;`,
  `SELECT * FROM xmltable('//person' PASSING '<person><name>Alice</name></person>' COLUMNS name text PATH 'name');`,
  `SELECT metric_name, count(*), avg(value) FROM metrics GROUP BY metric_name;`
];

